apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: history-rollback-demo
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: argocdappdemo
    server: "https://kubernetes.default.svc"
  source:
    path: Demo_Files/Nginx_Deployment
    repoURL: "https://github.com/tobsirl/argocd-example-apps.git"
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
